### ISSUE TITLE
Please provide me some more introduction information

### ISSUE THREAD

**Issue by guettli** [pennersr/netwell#1]
I came here from django-allauth.

I am interested in the netwell app.

I think I understand what netwell does. But I don't get the big picture.

Most people use a tool like nagios to run checks.

What is your intention? How to call the netwell scripts? Where do the results get stored?

**Comment by fmartingr** [comment]
I don't know if this helps, but I came here from django-allauth too and I'm using this tool to perform some automated checks in a jenkins instance, all of our developers can write "test cases" with this and extend the library if they want since it's pure python.

**Comment by pennersr** [comment]
My goal is to provide a basic monitoring solution that is dead-simple to setup and easy to extend. My intention is in no way to compete with full blown monitoring solutions such as Nagios.  

Results are not stored. You run the scripts as indicated in the README. Simply place it in a crontab and you'll get an email if something goes wrong. This way of working is perfectly fine for smaller projects, though it may not be everybody's cup of tea.

**Comment by guettli** [comment]
@pennersr thank you for explaining your intention.

I guess calling netwell from nagios/icinga should be simple.
