### ISSUE TITLE
Update pip version

### ISSUE THREAD

**Issue by Smarties89** [pennersr/netwell#5]
I know this project haven't been updated for 1 year, but it is awesome and should be kept alive!
Maybe you can update the pip version as it is running a outdated version?

Thank you
Martin

**Comment by pennersr** [comment]
It's still being maintained, although it covers most of my use cases, so there is little development going on. Here you go: 39152d9e1ab15a97be7fec61850484a73d1895ff  ...

**Comment by Smarties89** [comment]
Thank you Raymond!

It is very versatile, and covers all use cases, but I find some of my use cases require a little too much boilerplate code.
Are you open to accept pull requests? And if so would prefer larger pull request or pull request that only covers one feature?

**Comment by pennersr** [comment]
Contributions are welcome, though I cannot promise I end up putting everything in. It greatly depends on what it is you are contributing. In any case, please keep pull requests small so that we can have a separate discussion on a per feature basis.

**Comment by Smarties89** [comment]
Perfect :+1:  you will see some small pullrequest soon
