### ISSUE TITLE
Code does not allow use of local DNS server

### ISSUE THREAD

**Issue by ilosamart** [pennersr/netwell#9]
First of all, many thanks for this lib, it's simple and handy :1st_place_medal: 

Now for the issue, [this line](https://github.com/pennersr/netwell/blob/39152d9e1ab15a97be7fec61850484a73d1895ff/netwell/checkers.py#L230) makes impossible to use local/custom DNS servers.

I can make a PR fixing this if you allow me to :smile:

**Comment by pennersr** [comment]
Sure. I would prefer to get rid of an external command altogether and use some simple module for this...
